-- liquibase formatted sql

-- changeset Evergreen:1661785023861-1
CREATE TABLE "products" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "vendor_code" BIGINT, "name" VARCHAR(255), "last_buy_cost" BIGINT, "last_sell_cost" BIGINT, CONSTRAINT "products_pkey" PRIMARY KEY ("id"));

-- changeset Evergreen:1661785023861-2
CREATE TABLE "products_stores" ("product_id" BIGINT NOT NULL, "store_id" BIGINT NOT NULL, "count" BIGINT, CONSTRAINT "products_stores_pkey" PRIMARY KEY ("product_id", "store_id"));

-- changeset Evergreen:1661785023861-3
CREATE TABLE "receipts" ("id" BIGINT NOT NULL, "store_id" BIGINT, CONSTRAINT "receipts_pkey" PRIMARY KEY ("id"));

-- changeset Evergreen:1661785023861-4
CREATE TABLE "receipts_products" ("product_id" BIGINT NOT NULL, "receipt_id" BIGINT NOT NULL, "count" BIGINT, "cost" BIGINT, CONSTRAINT "receipts_products_pkey" PRIMARY KEY ("product_id", "receipt_id"));

-- changeset Evergreen:1661785023861-5
CREATE TABLE "sales" ("id" BIGINT NOT NULL, "store_id" BIGINT, CONSTRAINT "sales_pkey" PRIMARY KEY ("id"));

-- changeset Evergreen:1661785023861-6
CREATE TABLE "sales_products" ("product_id" BIGINT NOT NULL, "sale_id" BIGINT NOT NULL, "count" BIGINT, "cost" BIGINT, CONSTRAINT "sales_products_pkey" PRIMARY KEY ("product_id", "sale_id"));

-- changeset Evergreen:1661785023861-7
CREATE TABLE "stores" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255), CONSTRAINT "stores_pkey" PRIMARY KEY ("id"));

-- changeset Evergreen:1661785023861-8
CREATE TABLE "transfer_products" ("product_id" BIGINT NOT NULL, "transfer_id" BIGINT NOT NULL, "count" BIGINT, CONSTRAINT "transfer_products_pkey" PRIMARY KEY ("product_id", "transfer_id"));

-- changeset Evergreen:1661785023861-9
CREATE TABLE "transfers" ("id" BIGINT NOT NULL, "store_from_id" BIGINT, "store_to_id" BIGINT, CONSTRAINT "transfers_pkey" PRIMARY KEY ("id"));

-- changeset Evergreen:1661785023861-10
ALTER TABLE "receipts" ADD CONSTRAINT "fk_receipts_on_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Evergreen:1661785023861-11
ALTER TABLE "transfers" ADD CONSTRAINT "fk_sales_on_store_from_id" FOREIGN KEY ("store_from_id") REFERENCES "stores" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Evergreen:1661785023861-12
ALTER TABLE "sales" ADD CONSTRAINT "fk_sales_on_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Evergreen:1661785023861-13
ALTER TABLE "transfers" ADD CONSTRAINT "fk_sales_on_store_to_id" FOREIGN KEY ("store_to_id") REFERENCES "stores" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Evergreen:1661785023861-14
ALTER TABLE "products_stores" ADD CONSTRAINT "products_stores_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- changeset Evergreen:1661785023861-15
ALTER TABLE "products_stores" ADD CONSTRAINT "products_stores_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "stores" ("id") ON UPDATE CASCADE ON DELETE NO ACTION;

-- changeset Evergreen:1661785023861-16
ALTER TABLE "receipts_products" ADD CONSTRAINT "receipts_products_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- changeset Evergreen:1661785023861-17
ALTER TABLE "receipts_products" ADD CONSTRAINT "receipts_products_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "receipts" ("id") ON UPDATE CASCADE ON DELETE NO ACTION;

-- changeset Evergreen:1661785023861-18
ALTER TABLE "sales_products" ADD CONSTRAINT "sales_products_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- changeset Evergreen:1661785023861-19
ALTER TABLE "sales_products" ADD CONSTRAINT "sales_products_sale_id_fkey" FOREIGN KEY ("sale_id") REFERENCES "sales" ("id") ON UPDATE CASCADE ON DELETE NO ACTION;

-- changeset Evergreen:1661785023861-20
ALTER TABLE "transfer_products" ADD CONSTRAINT "transfer_products_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- changeset Evergreen:1661785023861-21
ALTER TABLE "transfer_products" ADD CONSTRAINT "transfer_products_transfer_id_fkey" FOREIGN KEY ("transfer_id") REFERENCES "transfers" ("id") ON UPDATE CASCADE ON DELETE NO ACTION;

